dubbo:
  scan:
    base-packages: net.magicli
  application:
    name:  dubbo-demo-consumer
  registry:
    address: 127.0.0.1:2181
    group: demo-group
    protocol: zookeeper
    timeout: 20000 #timeout时间配置长一点，不然可能会超时，导致zk链接不上
  consumer:
    check: false
    timeout: 3000
  reference:
    check: false

#    dubbo.scan.base-packages=com.heygood
#    dubbo.application.name=${spring.dubbo.application.name}
#    dubbo.registry.address=${spring.dubbo.registry.address}
#    dubbo.registry.group=${spring.dubbo.registry.group}
#    dubbo.registry.protocol=zookeeper
#    dubbo.registry.timeout=20000
#    dubbo.consumer.check=false
#    dubbo.reference.check=false
#    dubbo.consumer.timeout=10000






#    spring.application.name=demo-spring-boot-dubbo-provider
#    spring.application.version=1.0
#
#    # 基于此包扫描生成 Dubbo 控件
#    dubbo.scan.basePackages=demo.spring.boot.dubbo.provider.service
#
#    dubbo.application.id=demo-spring-boot-dubbo-provider
#    dubbo.application.name=demo-spring-boot-dubbo-provider
#
#    dubbo.protocol.id=dubbo
#    dubbo.protocol.name=dubbo
#    dubbo.protocol.port=20880
#
#    dubbo.registry.id=demo-multicast-registry
#    dubbo.registry.address=multicast://224.5.6.7:1234

